#%RAML 1.0
title: Auth
baseUri: http://localhost:8080/auth/{version}
version: v1

/auth
  post:
    description: Authentication request.
    body:
      application/json:
        example: |
          {
            "grant_type": "id_token", 
            "idToken": "id_token",
            "email": "email@example.com", 
            "password": "password1234", 
            "scope": "default"
          }
      
    responses:
      200:
        body:
          application/json:
            $ref: '#/components/schemas/AccessToken'
            example: |
              {
                "email": "email@example.com",
                "token": "xxx.xxx.xxx"
                "name": "John D"
                "avatar": "http://example.com/pic"
              }
components:

  schemas:

    AccessToken:
      type: object
      description: JWT token to authorize users future requests within the scopes and validity time frame.
      properties:
        email:
          type: string
          description: ID value from the database user's record. Effective is the user's email address
        token:
          type: string
          description: The access token for the current user.
          example: AoFmNJLDTW8jQtGSJ1iZeeoLiwNZ2ihz3iiCHGpuvE439nppuY
        name:
          type: string
          description: The name of the user as given at the time of the user's registration
          example: John D
        avatar:
          $ref: '#/components/schemas/PictureUrl'

    UserProfile:
      type: object
      description: |-
        This is the schema of the object returned as response on GET in /users
      properties:
        email:
          $ref: '#/components/schemas/EmailAddress'
        picture_url:
          $ref: '#/components/schemas/PictureUrl'
        authorized:
          $ref: '#/components/schemas/AuthorizedFlag'
        name:
          $ref: '#/components/schemas/Username'
      required:
        - email
        - authorized
