steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'eu.gcr.io/ivmauth/ivmauth-staging', '.','--build-arg','GITHUB_TOKEN=${_GITHUB_TOKEN}','--build-arg','USERNAME=${_USERNAME}']
  timeout: 500s
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'eu.gcr.io/ivmauth/ivmauth-staging']
# Deploy container image to Cloud Run. All arguments here: https://cloud.google.com/sdk/gcloud/reference/run/deploy
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['beta', 'run', 'deploy', 'ivmauth-staging', 
    '--image', 'eu.gcr.io/ivmauth/ivmauth-staging', 
    '--region', 'europe-west4', 
    '--platform', 'managed', 
    '--memory', '1Gi', '--cpu', '2',
    # '--no-use-http2', 
    '--no-allow-unauthenticated', 
    '--service-account', 'ivmauth-staging@ivmauth.iam.gserviceaccount.com', 
    '--min-instances', '0', '--max-instances', '2',
    '--set-env-vars','FIRESTORE_PROJECT_ID=ivmauth']
images:
- eu.gcr.io/ivmauth/ivmauth-staging
