steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'eu.gcr.io/${PROJECT_ID}/ivmauth-staging', '.','--build-arg','GITHUB_TOKEN=${_GITHUB_TOKEN}','--build-arg','USERNAME=${_USERNAME}']
  timeout: 500s
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'eu.gcr.io/${PROJECT_ID}/ivmauth-staging']
# Deploy container image to Cloud Run. All arguments here: https://cloud.google.com/sdk/gcloud/reference/run/deploy
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['beta', 'run', 'deploy', 'ivmauth-staging', 
    '--image', 'eu.gcr.io/${PROJECT_ID}/ivmauth-staging', 
    '--region', 'europe-west4', 
    '--platform', 'managed', 
    '--memory', '1Gi', '--cpu', '2',
    # '--no-use-http2', 
    #'--no-allow-unauthenticated', 
    '--allow-unauthenticated',
    '--ingress', 'internal-and-cloud-load-balancing',
    '--vpc-connector', 'ivm-svrls-con-1',
    '--service-account', 'ivmauth-staging@${PROJECT_ID}.iam.gserviceaccount.com', 
    '--min-instances', '0', '--max-instances', '4',
    '--set-env-vars','FIRESTORE_PROJECT_ID=${_FIRESTORE_PROJECT_ID}, SMTP_PASSWORD=${_SMTP_PASSWORD}']
images:
- eu.gcr.io/${PROJECT_ID}/ivmauth-staging
