# ivmauth service configuration file

# environment
env: 
  env_type: staging
  cid: "xxx.apps.ivmanto.dev:ivmanto-2021"
  csc: "ivmanto-2021"

# server configuration
server:
  host: '127.0.0.1'
  port: ${PORT}

# cloud environment config
cloud_env:
  project_id: 'ivmauth'

# access token config
atc:
  validity: 3600
  realm:    "ivmanto.com"
  alg:      "RS256"
  issuer:   "https://accounts.ivmanto.com"
