# ivmauth service configuration file

# environment
env: STAGING

# current service configuration
auth_svc:
  host: ["ivmauth-staging-3fu5utwshq-ez.a.run.app"]
  port: ${PORT}

# cloud environment config
cloud_env:
  project_id: 'ivmauth'

# session man config
sesman_config:
  cookie_name: "ivmid"
  max_lifetime: 3600
  visit_cookie_name: "iv"
  project_id: $FIRESTORE_PROJECT_ID

# api-gateway config
api_gateway_svc:
  host: ["ivmanto.dev"]
  endpoints:
    - endpoint: "/pg/cb"
      method: "GET"

# web application config
web_app_svc:
  # Configuring the wep app service
  name: webAppSvc
  endpoints: []
  timeout: 60
  host: ["ivmanto-com-xmywgxnrfq-ez.a.run.app"]
  version: 0.0.3

# access token config
at_config:
  validity: 3600
  realm:    "ivmanto.com"
  alg:      "RS256"
  issuer:   "https://accounts.ivmanto.dev"

# supported OpenID Providers
oidps:
  - "ivmanto"
  - "google"
  - "github"
  - "apple"

# ivmanto openID config
ivmanto_oidc:
  issuer: "https://accounts.ivmanto.dev"
  authorization_endpoint: "https://accounts.ivmanto.dev/oauth/v1/authorize"
  token_endpoint: "https://accounts.ivmanto.dev/oauth/v1/token"
  device_authorization_endpoint: ""
  revocation_endpoint: "https://accounts.ivmanto.dev/oauth/v1/revoke"
  jwks_uri: "https://ivmanto.dev/oauth2/v1/certs"
  token_endpoint_auth_methods_supported:
    - "client_secret_basic"
    - "private_key_jwt"
  token_endpoint_auth_signing_alg_values_supported:
    - "RS256"
    - "ES256"
  userinfo_endpoint: "https://accounts.ivmanto.dev/oauth/v1/userinfo"
  check_session_iframe: "https://accounts.ivmanto.dev/oauth/v1/check_session"
  end_session_endpoint: "https://accounts.ivmanto.dev/oauth/v1/end_session"
  egistration_endpoint: "https://accounts.ivmanto.dev/oauth/v1/register"
  scopes_supported:
    - "openid"
    - "profile"
    - "email"
    - "address"
    - "phone"
    - "offline_access"
  response_types_supported:
    - "code"
    - "code id_token"
    - "id_token"
    - "token id_token"
  
  # ["urn:mace:incommon:iap:silver", "urn:mace:incommon:iap:bronze"]
  acr_values_supported: []

  # ["public", "pairwise"]
  subject_types_supported: []

  # ["RS256", "ES256", "HS256"]
  userinfo_signing_alg_values_supported:
    - "RS256"

  # ["RSA1_5", "A128KW"]
  userinfo_encryption_alg_values_supported: []

  # ["A128CBC-HS256", "A128GCM"]
  userinfo_encryption_enc_values_supported: []

  # ["RS256", "ES256", "HS256"]
  id_token_signing_alg_values_supported: []

  # ["RSA1_5", "A128KW"]
  id_token_encryption_alg_values_supported: []

  # ["A128CBC-HS256", "A128GCM"]
  id_token_encryption_enc_values_supported: []

  # ["none", "RS256", "ES256"]
  request_object_signing_alg_values_supported:

  # ["page", "popup"]
  display_values_supported:
    
  # ["normal", "distributed"]
  claim_types_supported:

  # ["sub", "iss", "auth_time", "acr","name", "given_name", "family_name", "nickname", "profile", "picture", "website", "email","email_verified", "locale", "zoneinfo", "http://example.info/claims/groups"]
  claims_supported:
    - "iss"
    - "sub"

  # false, true
  claims_parameter_supported: true
  service_documentation: "https://accounts.ivmanto.dev/oauth/v1/docs.html"
  
  # ["en-US", "en-GB", "en-CA", "fr-FR", "fr-CA"]
  ui_locales_supported:
    - "en-US"
  
  # ["plain", "S256"]
  code_challenge_methods_supported:
    - "S256"
  
  # ["authorization_code", "refresh_token","urn:ietf:params:oauth:grant-type:device_code","urn:ietf:params:oauth:grant-type:jwt-bearer"]
  grant_types_supported:
    - "authorization_code"
    - "refresh_token"
